In [10]:
from resnet50 import ResNet50
from keras.preprocessing import image
import keras.backend as K
import numpy as np


### Loading Images

In [4]:
trail_images = np.zeros((2,224,224,3))
trail_images[0] = image.array_to_img(image.load_img('trail_images/1_1.jpg'))
trail_images[1] = image.array_to_img(image.load_img('trail_images/1_2.jpg'))

### Loading Model
Note: that this model can be reproduced by using keras.applications

In [5]:
model = ResNet50(include_top=False, weights='imagenet')

### Inference

In [6]:
embs = model.predict(trail_images)

In [7]:
embs = embs.squeeze()
embs[0][0:100]

array([  5.66334650e-03,   8.14079523e-01,   1.11252833e-02,
         2.49515414e+00,   0.00000000e+00,   3.12298119e-01,
         6.72828734e-01,   7.97079504e-03,   6.85831726e-01,
         3.83406967e-01,   4.52610105e-01,   1.46672547e-01,
         4.70056646e-02,   0.00000000e+00,   9.05495882e-01,
         1.57297403e-01,   0.00000000e+00,   3.85352746e-02,
         0.00000000e+00,   0.00000000e+00,   1.68608144e-01,
         6.64086103e-01,   1.68223426e-01,   6.17932156e-02,
         1.90472916e-01,   6.45114839e-01,   2.05633402e-01,
         3.38879903e-03,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   7.08613753e-01,   0.00000000e+00,
         3.12051475e-01,   3.45117673e-02,   5.24696767e-01,
         7.75095373e-02,   1.47262895e+00,   6.24355301e-02,
         3.28966618e-01,   0.00000000e+00,   2.90383071e-01,
         3.04302797e-02,   0.00000000e+00,   1.86312780e-01,
         9.55196992e-02,   1.34004414e+00,   4.61207666e-02,
         6.22883327e-02,

### Trying preprocessing as suggested
function is taken from keras.applications.imagenet_utils

In [8]:
def preprocess_input(x, data_format=None, mode='caffe'):
    """Preprocesses a tensor encoding a batch of images.
    # Arguments
        x: input Numpy tensor, 4D.
        data_format: data format of the image tensor.
        mode: One of "caffe", "tf".
            - caffe: will convert the images from RGB to BGR,
                then will zero-center each color channel with
                respect to the ImageNet dataset,
                without scaling.
            - tf: will scale pixels between -1 and 1,
                sample-wise.
    # Returns
        Preprocessed tensor.
    """
    if data_format is None:
        data_format = K.image_data_format()
    assert data_format in {'channels_last', 'channels_first'}

    if mode == 'tf':
        x /= 255.
        x -= 0.5
        x *= 2.
        return x

    if data_format == 'channels_first':
        if x.ndim == 3:
            # 'RGB'->'BGR'
            x = x[::-1, ...]
            # Zero-center by mean pixel
            x[0, :, :] -= 103.939
            x[1, :, :] -= 116.779
            x[2, :, :] -= 123.68
        else:
            x = x[:, ::-1, ...]
            x[:, 0, :, :] -= 103.939
            x[:, 1, :, :] -= 116.779
            x[:, 2, :, :] -= 123.68
    else:
        # 'RGB'->'BGR'
        x = x[..., ::-1]
        # Zero-center by mean pixel
        x[..., 0] -= 103.939
        x[..., 1] -= 116.779
        x[..., 2] -= 123.68
    return x

In [11]:
trail_images2 = np.zeros((2,224,224,3))
trail_images2[0] = preprocess_input(trail_images[0])
trail_images2[1] = preprocess_input(trail_images[1])

In [16]:
embs2 = model.predict(trail_images2)
embs2 = embs2.squeeze()
embs2[0][0:100]

array([  0.00000000e+00,   8.32485974e-01,   3.57342176e-02,
         4.71976566e+00,   0.00000000e+00,   5.01036346e-01,
         1.13746357e+00,   6.80260267e-03,   9.69435394e-01,
         4.02510881e-01,   4.25002337e-01,   3.68344635e-01,
         2.59720478e-02,   0.00000000e+00,   1.33642220e+00,
         2.89050162e-01,   0.00000000e+00,   4.08360541e-01,
         0.00000000e+00,   0.00000000e+00,   4.13491070e-01,
         4.54705149e-01,   2.63358951e-01,   2.11133048e-01,
         1.45672426e-01,   6.45071208e-01,   1.04144223e-01,
         0.00000000e+00,   2.83974390e-02,   0.00000000e+00,
         0.00000000e+00,   3.93708535e-02,   7.18003809e-02,
         5.55889249e-01,   0.00000000e+00,   1.41675577e-01,
         0.00000000e+00,   3.90557081e-01,   3.26747745e-01,
         1.08520162e+00,   3.87041643e-02,   5.27665019e-01,
         2.10631755e-03,   6.59319460e-02,   0.00000000e+00,
         6.59667403e-02,   7.80317008e-01,   0.00000000e+00,
         1.19890064e-01,

### Now trying with preprocessing mode = tf

In [13]:
trail_images3 = np.zeros((2,224,224,3))
trail_images3[0] = preprocess_input(trail_images[0],mode="tf")
trail_images3[1] = preprocess_input(trail_images[1],mode="tf")

In [17]:
embs3 = model.predict(trail_images3)
embs3 = embs3.squeeze()
embs3[0][0:100]

array([  0.00000000e+00,   0.00000000e+00,   4.12747310e-03,
         0.00000000e+00,   5.50312817e-01,   0.00000000e+00,
         0.00000000e+00,   7.26377189e-01,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   7.85149217e-01,
         1.47083094e-02,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   3.65573051e-03,   0.00000000e+00,
         9.32822097e-03,   6.06841087e-01,   0.00000000e+00,
         4.87885140e-02,   0.00000000e+00,   2.54396768e-03,
         0.00000000e+00,   0.00000000e+00,   3.25301848e-03,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   7.38765225e-02,
         0.00000000e+00,   5.33546805e-02,   1.28633052e-01,
         0.00000000e+00,   2.07603700e-03,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   1.37142983e-04,
         0.00000000e+00,